apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'helloworld-imagestream:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: 'https://github.com/eeetanju/nginxtest.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:latest'
        namespace: openshift
    type: Source
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
