apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  generation: 1
  labels:
    app: helloworld
  name: helloworld-imagestream
  resourceVersion: '821267'
spec:
  lookupPolicy:
    local: false
